spring:
  application:
    name: dps-kafka-producer

  Kafka:
    bootstrap:
      servers: localhost:9092
    properties:
      spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:5432/user-created
    driver-class-name: org.postgresql.Driver
    username: usuario
    password: senha123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081