spring:
  application:
    name: dps-kafka-producer

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap:
      servers: localhost:${KAFKA_PORT}
    producer:
      topic:
        kafka-topic: "topic-user-v1"

server:
  port: 8083

#logging:
#  level:
#    org.apache.kafka: DEBUG