spring:
  application:
    name: dps-kafka-producer

  datasource:
    url: jdbc:postgresql://localhost:5432/user-created
    driver-class-name: org.postgresql.Driver
    username: usuario
    password: senha123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap:
      servers: localhost:9092

server:
  port: 8081

#logging:
#  level:
#    org.apache.kafka: DEBUG